objects=\
er9b_downsample_image.o\
er9b_downsample_image_dimensions.o\
er9b_error_handler.o\
feature_add_feature.o\
feature_add_features.o\
feature_adjust_features_image_doubling.o\
feature_build_dog_space.o\
feature_build_scale_space.o\
feature_check_extremum_edge_like.o\
feature_compute_descriptors.o\
feature_compute_features_orientation_histogram.o\
feature_compute_features_sigma.o\
feature_create_init_image.o\
feature_descriptor_convert_histogram.o\
feature_descriptor_histogram.o\
feature_descriptor_histogram_interpolate.o\
feature_descriptor_normalize.o\
feature_detect_features.o\
feature_dog_deriv.o\
feature_dog_hessian.o\
feature_get_dominant_orientation.o\
feature_gradient_magnitude_orientation.o\
feature_interpolate_extremum_location.o\
feature_interpolate_extremum_location_main.o\
feature_is_extremum.o\
feature_main.o\
feature_orientation_histogram.o\
feature_show_features.o\
feature_smooth_orientation_histogram.o\
gaussian_blur_image.o\
homography_apply.o\
homography_main.o\
interpolate_bicubic.o\
interpolate_bicubic_rgb.o\
interpolate_cubic.o\
match_distance_squared.o\
match_feature.o\
match_features.o\
match_main.o\
match_show_matches.o\
orsa_best_number_false_alarms.o\
orsa_characteristic_polynomial.o\
orsa_compute_sort_errors.o\
orsa_epipolar.o\
orsa_find_cubic_roots.o\
orsa_log_combi.o\
orsa_main.o\
orsa_pick_7_random_matches.o\
rectify_compress.o\
rectify_compute_disp_range_b.o\
rectify_compute_disp_range.o\
rectify_compute_fundamental_matrix.o\
rectify_compute_inverse_k_matrix.o\
rectify_compute_inverse_k_matrix_deriv.o\
rectify_compute_k_matrix.o\
rectify_compute_rotation.o\
rectify_compute_rotation_deriv.o\
rectify_compute_rotation_left.o\
rectify_compute_rotation_right.o\
rectify_compute_sampson_error.o\
rectify_compute_sampson_error_jacobian.o\
rectify_compute_vertical_disparity_error.o\
rectify_fix_center.o\
rectify_main.o\
rectify_minimize_sampson_error.o\
rectify_uncompress.o\
rgb_to_grayscale.o
